interface QrCodeModalProps {
  guestName: string
  invitationCode: string
  qrCodeDataUrl?: string
  onClose: () => void
}

/**
 * QR Code Pass Modal component for event check-in.
 * Displays QR code generated by backend QrCodeService.
 */
export function QrCodeModal({ guestName, invitationCode, qrCodeDataUrl, onClose }: QrCodeModalProps) {
  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center p-4 z-50">
      <div className="card w-full max-w-sm bg-surface border border-white/10 p-6 text-center shadow-2xl">
        <h3 className="text-xl font-bold text-white mb-1">Your Digital Event Pass</h3>
        <p className="text-slate-400 text-xs mb-6">Show this QR code at the entrance for quick check-in.</p>

        {qrCodeDataUrl ? (
          <div className="bg-white p-4 rounded-2xl inline-block shadow-lg mb-4">
            <img src={qrCodeDataUrl} alt="Event Check-In QR Code" className="w-56 h-56 mx-auto" />
          </div>
        ) : (
          <div className="w-56 h-56 bg-white/5 rounded-2xl flex items-center justify-center mx-auto mb-4 text-slate-400 text-sm">
            Generating Pass…
          </div>
        )}

        <p className="text-lg font-semibold text-white mb-1">{guestName}</p>
        <p className="text-xs font-mono text-primary-400 mb-6">Code: {invitationCode}</p>

        <button onClick={onClose} className="btn-primary w-full">
          Close Pass
        </button>
      </div>
    </div>
  )
}
