spring:
  config:
    activate:
      on-profile: test

  datasource:
    # Testcontainers will override this dynamically
    url: jdbc:tc:postgresql:16:///HIMPACT_DB
    username: himpact_test
    password: hamdy
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: true

logging:
  level:
    com.himpact: DEBUG
