spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/HIMPACT_DB
    username: himpact_dev
    password: hamdy

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true

  devtools:
    restart:
      enabled: true

server:
  port: 8080

himpact:
  security:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:3000

logging:
  level:
    com.himpact: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
